name: flutter_fruta
description: A new Flutter project.

publish_to: 'none'

version: 3.0.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  animated_background: ^2.0.0
  cupertino_icons: ^1.0.6
  # cupertino_list_tile: ^0.2.1+1
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  macos_ui: ^2.0.0
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.2
  flutter_native_splash: ^2.3.8
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  macos:
    generate: true
    image_path: "assets/icon.png"

flutter_native_splash:
  color: "#E596B5"
  image: "assets/icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/smoothie/
    - assets/ingredients/
