name: flutter_fruta
description: A new Flutter project.

publish_to: 'none'

version: 2.0.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_background: ^2.0.0
  cupertino_icons: ^1.0.3
  cupertino_list_tile: ^0.2.0
  flip_card: ^0.5.0
  hive: ^2.0.4
  hive_flutter: ^1.0.0
  modal_bottom_sheet: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  pedantic: ^1.11.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/smoothie/
    - assets/ingredients/
