# This is a basic workflow to help you get started with Actions

name: FrutaiOSProfileBuild

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3.5.3
   # - uses: actions/setup-java@v3.12.0
    - uses: subosito/flutter-action@v2.10.0
      with:
        channel: 'stable'
    - run: flutter pub get
    
    - name: Build iOS App
      run: |
          flutter build ipa --profile --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
    
    # Upload generated ipa to the artifacts.
    - uses: actions/upload-artifact@v3.1.2
      with:
        name: profile-ipa
        path: build/ios/iphoneos/Runner.app 
