name: FrutaiOSReleaseBuild

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3.5.3
    - uses: subosito/flutter-action@v2.10.0
      with:
        channel: 'stable'
    - run: flutter pub get
    
    - name: Build iOS App with Release Mode
      run: |
          flutter build ipa --release --no-codesign
          cd build/ios/ipa
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload
    
    # Upload generated ipa to the artifacts.
    - uses: actions/upload-artifact@v3.1.2
      with:
        name: release-ipa
        path: build/ios/iphoneos/app.ipa 
